# **Data Pre-Processing**

## 1. Introduction

## 2. Combining Dataset of All Jabodetabek

In [2]:
import pandas as pd
import numpy as np
from numpy import vectorize
import ast

In [3]:
file_names = [
    'Scraped_Data/Bekasi_2022-10-09_16-57_page_1_to_50.csv',
    'Scraped_Data/Bogor_2022-10-08_17-49_page_1_to_20.csv',
    'Scraped_Data/Bogor_2022-10-08_18-19_page_21_to_30.csv',
    'Scraped_Data/Bogor_2022-10-09_18-20_page_31_to_50.csv',
    'Scraped_Data/Depok_2022-10-09_17-17_page_1_to_21.csv',
    'Scraped_Data/Depok_2022-10-09_14-23_page_22_to_50.csv',
    'Scraped_Data/Jakarta_2022-10-07_08-14_page_1_to_10.csv',
    'Scraped_Data/Jakarta_2022-10-08_13-34_page_11_to_20.csv',
    'Scraped_Data/Jakarta_2022-10-09_17-20_page_21_to_37.csv',
    'Scraped_Data/Jakarta_2022-10-08_15-00_page_38_to_40.csv',
    'Scraped_Data/Jakarta_2022-10-08_15-41_page_41_to_50.csv',
    'Scraped_Data/Tangerang_2022-10-08_21-10_page_1_to_50.csv'
]

df = pd.concat(
    map(pd.read_csv, file_names), ignore_index=True
)

df.sample(2).T

2719  \
url                   https://www.rumah123.com/properti/tangerang/ho...   
currency                                                             Rp   
price                                                              4,27   
price_unit_scale                                                 Miliar   
title                 Dekat Clubhouse, Dapat Extra Tanah, Dijamin Ha...   
address                                          Alam Sutera, Tangerang   
facilities             Keamanan,  Jogging Track, Taman, Ac,  CCTV,  ...   
k. tidur                                                            3.0   
k. mandi                                                            2.0   
l. tanah                                                         200 m²   
l. bangunan                                                      155 m²   
tipe properti                                                     rumah   
sertifikat                                                          NaN   
daya listrik                                                   3500 mah   
km. pembantu                                                        1.0   
jumlah lantai                                                       2.0   
tahun dibangun                                                   2021.0   
kondisi properti                                                   baru   
kondisi perabotan                                        semi furnished   
id iklan                                                    hos10835383   
carport                                                             2.0   
hadap                                                             timur   
garasi                                                              NaN   
kt. pembantu                                                        1.0   
bedrooms                                                            NaN   
bathrooms                                                           NaN   
land size                                                           NaN   
building size                                                       NaN   
carports                                                            NaN   
certificate                                                         NaN   
electricity                                                         NaN   
maid bedrooms                                                       NaN   
maid bathrooms                                                      NaN   
floors                                                              NaN   
building age                                                        NaN   
property condition                                                  NaN   
building orientation                                                NaN   
garages                                                             NaN   
furnishing                                                          NaN   

                                                                   3526  
url                   https://www.rumah123.com/properti/tangerang/ho...  
currency                                                             Rp  
price                                                               3,5  
price_unit_scale                                                 Miliar  
title                 Rumah Modern Brand New Jln Adam Malik Perbatas...  
address                                             Larangan, Tangerang  
facilities            Masjid,  Taman, Lapangan Tenis, Kitchen Set, K...  
k. tidur                                                            4.0  
k. mandi                                                            4.0  
l. tanah                                                         163 m²  
l. bangunan                                                      220 m²  
tipe properti                                                     rumah  
sertifikat                                   shm - sertifikat hak milik  
daya listrik                  

## 3. Column Field Correction

As we can see, there are inconsistence column labels due to different language format. Let's compare both condition:

In [4]:
list((df[~(df['k. tidur'].isna())].sample(1).index.values,
        df[~(df['bedrooms'].isna())].sample(1).index.values)
)

[array([2367], dtype=int64), array([299], dtype=int64)]

In [5]:
sample = pd.concat([
        df[(df['k. tidur'].notnull())].sample(1),
        df[(df['bedrooms'].notnull())].sample(1)
])

sample.T

2953  \
url                   https://www.rumah123.com/properti/tangerang/ho...   
currency                                                             Rp   
price                                                               660   
price_unit_scale                                                   Juta   
title                 Rumah Strategis di Perum Dasana Indah Dekat Su...   
address                                           Kelapa Dua, Tangerang   
facilities                                              Keamanan, Taman   
k. tidur                                                            3.0   
k. mandi                                                            2.0   
l. tanah                                                          60 m²   
l. bangunan                                                       72 m²   
tipe properti                                                     rumah   
sertifikat                                   shm - sertifikat hak milik   
daya listrik                                                   1300 mah   
km. pembantu                                                        NaN   
jumlah lantai                                                       1.0   
tahun dibangun                                                      NaN   
kondisi properti                                                  bagus   
kondisi perabotan                                           unfurnished   
id iklan                                                    hos11036772   
carport                                                             1.0   
hadap                                                             barat   
garasi                                                              NaN   
kt. pembantu                                                        NaN   
bedrooms                                                            NaN   
bathrooms                                                           NaN   
land size                                                           NaN   
building size                                                       NaN   
carports                                                            NaN   
certificate                                                         NaN   
electricity                                                         NaN   
maid bedrooms                                                       NaN   
maid bathrooms                                                      NaN   
floors                                                              NaN   
building age                                                        NaN   
property condition                                                  NaN   
building orientation                                                NaN   
garages                                                             NaN   
furnishing                                                          NaN   

                                                                   10    
url                   https://www.rumah123.com/properti/bekasi/hos10...  
currency                                                             Rp  
price                                                               920  
price_unit_scale                                                   Juta  
title                 Rumah Murah di jatiwaringin 2 lantai  Bebas ba...  
address                                             Pondok Gede, Bekasi  
facilities                                   CCTV, Ac,  Taman, Keamanan  
k. tidur                                                            NaN  
k. mandi                                                            NaN  
l. tanah                                                            NaN  
l. bangunan                                                         NaN  
tipe properti                                                     rumah  
sertifikat                                                          NaN  
daya listrik                  

In [6]:
row_count = pd.DataFrame({
    'row_count' : [
        df[df['k. tidur'].notnull()].shape[0],
        df[df['bedrooms'].notnull()].shape[0]
        ]
    })
row_count.index=['ind_labeled', 'eng_labeled']
row_count

row_count
ind_labeled       3409
eng_labeled        110

As we can see, where `Indonesian labeled column` is recorded, the `English labeled column` is empty, and vice versa. I decide to keep the English label using codes below:

In [7]:
label_pair = [
    ('k. tidur', 'bedrooms'),
    ('k. mandi', 'bathrooms'),
    ('l. tanah', 'land size'),
    ('l. bangunan', 'building size'),
    ('sertifikat', 'certificate'),
    ('daya listrik', 'electricity'),
    ('km. pembantu', 'maid bathrooms'),
    ('jumlah lantai', 'floors'),
    ('tahun dibangun', 'building age'),
    ('kondisi properti', 'property condition'),
    ('kondisi perabotan', 'furnishing'),
    ('carport', 'carports'),
    ('hadap', 'building orientation'),
    ('garasi', 'garages'),
    ('kt. pembantu', 'maid bedrooms')
]

We will use `DataFrame.fillna()` (column-wise) to fill missing records of `English labeled columns` using `Indonesian labeled columns` value as below:

In [8]:
for ind, eng in label_pair:
    df[eng].fillna(value=df[ind], inplace=True)
df.sample(2).T

2877  \
url                   https://www.rumah123.com/properti/tangerang/ho...   
currency                                                             Rp   
price                                                              1,02   
price_unit_scale                                                 Miliar   
title                 Rumah Minimalis Bebas Banjir di Serpong Garden...   
address                                               Cisauk, Tangerang   
facilities                                              Keamanan, Taman   
k. tidur                                                            2.0   
k. mandi                                                            2.0   
l. tanah                                                          84 m²   
l. bangunan                                                       54 m²   
tipe properti                                                     rumah   
sertifikat                                                          NaN   
daya listrik                                                   1300 mah   
km. pembantu                                                        NaN   
jumlah lantai                                                       1.0   
tahun dibangun                                                      NaN   
kondisi properti                                                    NaN   
kondisi perabotan                                           unfurnished   
id iklan                                                    hos10612885   
carport                                                             NaN   
hadap                                                               NaN   
garasi                                                              1.0   
kt. pembantu                                                        1.0   
bedrooms                                                            2.0   
bathrooms                                                           2.0   
land size                                                         84 m²   
building size                                                     54 m²   
carports                                                            NaN   
certificate                                                         NaN   
electricity                                                    1300 mah   
maid bedrooms                                                       1.0   
maid bathrooms                                                      NaN   
floors                                                              1.0   
building age                                                        NaN   
property condition                                                  NaN   
building orientation                                                NaN   
garages                                                             1.0   
furnishing                                                  unfurnished   

                                                                   475   
url                   https://www.rumah123.com/properti/bekasi/hos11...  
currency                                                             Rp  
price                                                               1,3  
price_unit_scale                                                 Miliar  
title                 Dijual Cepat Rumah Dalam Cluster Terdepan di H...  
address                                           Harapan Indah, Bekasi  
facilities                                       Keamanan 24 jam, Taman  
k. tidur                                                            2.0  
k. mandi                                                            2.0  
l. tanah                                                          90 m²  
l. bangunan                                                       90 m²  
tipe properti                                                     rumah  
sertifikat                                   shm - sertifikat hak milik  
daya listrik                  

Looks like it turns out as we expected. Now we just drop the `Indonesian labeled columns` using below codes. We also rename the columns that still in Indonesian label and using `snake_case` format:

In [9]:
for column in label_pair:
    df.drop(labels=column[0], axis=1, inplace=True)

df.rename(
    columns={
        'tipe properti': 'property_type',
        'id iklan': 'ads_id'
        }, 
    inplace=True
)

df.rename(
    columns={
        column: column.replace(' ', '_') for column in df.columns
    },
    inplace=True
)

df.sample(2).T

2839  \
url                   https://www.rumah123.com/properti/tangerang/ho...   
currency                                                             Rp   
price                                                               7,1   
price_unit_scale                                                 Miliar   
title                 RUMAH SULTAN TERMEWAH DAPAT BATHTUBE WHIRLPOOL...   
address                                       Gading Serpong, Tangerang   
facilities             Ac,  Taman, Jogging Track, Keamanan,  CCTV,  ...   
property_type                                                     rumah   
ads_id                                                       hos9813160   
bedrooms                                                            4.0   
bathrooms                                                           3.0   
land_size                                                        214 m²   
building_size                                                    230 m²   
carports                                                            2.0   
certificate                                                         NaN   
electricity                                                    5500 mah   
maid_bedrooms                                                       1.0   
maid_bathrooms                                                      NaN   
floors                                                              2.0   
building_age                                                     2022.0   
property_condition                                                 baru   
building_orientation                                            selatan   
garages                                                             1.0   
furnishing                                               semi furnished   

                                                                   2123  
url                   https://www.rumah123.com/properti/jakarta-bara...  
currency                                                             Rp  
price                                                               528  
price_unit_scale                                                   Juta  
title                 Rumah Minimalis Murah di Jl. Taman Sari  Jakar...  
address                                        Tamansari, Jakarta Barat  
facilities                                               Keamanan, CCTV  
property_type                                                     rumah  
ads_id                                                      hos11034253  
bedrooms                                                            2.0  
bathrooms                                                           2.0  
land_size                                                         22 m²  
building_size                                                     42 m²  
carports                                                            NaN  
certificate                                  shm - sertifikat hak milik  
electricity                                                    2200 mah  
maid_bedrooms                                                       NaN  
maid_bathrooms                                                      NaN  
floors                                                              2.0  
building_age                                                     2022.0  
property_condition                                                 baru  
building_orientation                                              timur  
garages                                                             NaN  
furnishing                                                  unfurnished

## 4. Transforming Price and Address Records

#### **Price Records**

We are going to check unique values of `currency` and `price_unit_scale`:

In [10]:
print(df.currency.unique())
print(df.price_unit_scale.unique())

['Rp']
['Miliar' 'Juta' 'Triliun']


We should check the house price in `Triliun`, since the value is rather ambiguous for a house price to be this high.

In [11]:
df[df.price_unit_scale=='Triliun']

url currency price  \
934  https://www.rumah123.com/properti/bogor/hos113...       Rp   5,4   

    price_unit_scale                                              title  \
934          Triliun  Rumah di Baranang Siang Indah, Dekat Tol, Mal,...   

                  address                                         facilities  \
934  Baranangsiang, Bogor  Taman, Keamanan 24 jam,  Taman,  CCTV, Masjid,...   

    property_type       ads_id  bedrooms  ...                 certificate  \
934         rumah  hos11359992       3.0  ...  shm - sertifikat hak milik   

    electricity maid_bedrooms  maid_bathrooms floors building_age  \
934    5500 mah           1.0             1.0    2.0          NaN   

     property_condition  building_orientation  garages   furnishing  
934               bagus                 timur      1.0  unfurnished  

[1 rows x 24 columns]

After checking the URL, seems that price is in Rp. 5,4 Miliar (listing may be revised by owner) so we shall revise the price scale for this record.

In [12]:
df.loc[df.price_unit_scale=='Triliun', 'price_unit_scale'] = 'Miliar'
print(df.price_unit_scale.unique())

['Miliar' 'Juta']


The price is still in `string` format, so we will transform the value by its `price_unit_scale`.

Pandas need `vectorized function` to execute `vectorized operations`. We can create `vectorized function` by creating a standard function first then we convert it into vectorized function using `np.vectorize`. Note that `np.vectorize` returns a `callable` as its output, which we will use to our Pandas operations.

In [13]:
def convert_price(price: str, unit_scale: str):
    price_numeric = float(price.replace(',', '.'))
    if unit_scale == 'Juta':
        converted_price = price_numeric * 1000000
    else:
        converted_price = price_numeric * 1000000000
    return converted_price

convert_price_vectd = vectorize(convert_price)

Let's try our `vectorized function` to our dataframe:

In [14]:
df.assign(
    price_converted=convert_price_vectd(df.price, df.price_unit_scale)
).loc[:, ['currency', 'price', 'price_unit_scale', 'price_converted']].sample(3, random_state=4).T

1893         1739          3275
currency                    Rp           Rp            Rp
price                     1,67          800           2,4
price_unit_scale        Miliar         Juta        Miliar
price_converted   1670000000.0  800000000.0  2400000000.0

As expected, `Pandas` performing vectorized function, resulting in an index-wise operation to convert the price. The scale of `Miliar` and `Juta` is also correct as expected.

We won't need the `price_unit_scale` anymore, and we will define a new column `price_in_rp` to inform that the currency is in `Rupiahs`.

In [15]:
df = df.assign(
    price = convert_price_vectd(df.price, df.price_unit_scale)
    ).rename(
        columns={'price': 'price_in_rp'}
    ).drop(
        ['currency', 'price_unit_scale'], axis=1
    )

df.sample(2).T

3417  \
url                   https://www.rumah123.com/properti/tangerang/ho...   
price_in_rp                                                3100000000.0   
title                 Dijual Rumah Nyaman dan Asri di Komplek Kejaks...   
address                                                 Kreo, Tangerang   
facilities                                              Keamanan, Taman   
property_type                                                     rumah   
ads_id                                                      hos11364619   
bedrooms                                                            4.0   
bathrooms                                                           3.0   
land_size                                                        175 m²   
building_size                                                    220 m²   
carports                                                            NaN   
certificate                                  shm - sertifikat hak milik   
electricity                                                    5500 mah   
maid_bedrooms                                                       1.0   
maid_bathrooms                                                      1.0   
floors                                                              2.0   
building_age                                                     2015.0   
property_condition                                                bagus   
building_orientation                                              utara   
garages                                                             2.0   
furnishing                                               semi furnished   

                                                                   1271  
url                   https://www.rumah123.com/properti/bogor/hos110...  
price_in_rp                                                1100000000.0  
title                 Rumah murah view gunung cluster Cadenza Sentul...  
address                                              Sentul City, Bogor  
facilities                         Jalur Telepon, Taman,  Keamanan,  AC  
property_type                                                     rumah  
ads_id                                                      hos11086151  
bedrooms                                                            2.0  
bathrooms                                                           2.0  
land_size                                                         90 m²  
building_size                                                     60 m²  
carports                                                            1.0  
certificate                                  shm - sertifikat hak milik  
electricity                                                    1300 mah  
maid_bedrooms                                                       NaN  
maid_bathrooms                                                      NaN  
floors                                                              1.0  
building_age                                                     2019.0  
property_condition                                                bagus  
building_orientation                                              utara  
garages                                                             NaN  
furnishing                                               semi furnished

#### **Address**

Address records contains (`district`, `city`). Splitting into this may be useful when reporting insight, so I will also provide the separate value of this.

In [16]:
def get_district(address:str):
    return address.strip().split(sep=',')[0]

def get_city(address:str):
    return address.strip().split(sep=',')[1]

get_district_vectd = vectorize(get_district)
get_city_vectd = vectorize(get_city)

In [17]:
df.assign(
    district=get_district_vectd(df.address),
    city=get_city_vectd(df.address)
).loc[:, ['address', 'district', 'city']].sample(3).T

3448           1448                2755
address   Cimone, Tangerang  Parung, Bogor  Ciledug, Tangerang
district             Cimone         Parung             Ciledug
city              Tangerang          Bogor           Tangerang

Results is as expected. We will apply this to our Dataframe, and positions the `district` and `city` next to the `address` for convenience.

In [18]:
columns_pair = [('city', get_city_vectd), ('district', get_district_vectd)]
for (col, func) in columns_pair:
    df.insert(4, col, func(df.address))

df.sample(2).T

3469  \
url                   https://www.rumah123.com/properti/tangerang/ho...   
price_in_rp                                                 700000000.0   
title                 Dijual Disewa Rumah di East Portofino, Villagg...   
address                                    Cikupa Citra Raya, Tangerang   
district                                              Cikupa Citra Raya   
city                                                          Tangerang   
facilities            Jalur Telepon, Taman,  One Gate System, Keaman...   
property_type                                                     rumah   
ads_id                                                      hos11363705   
bedrooms                                                            2.0   
bathrooms                                                           1.0   
land_size                                                         72 m²   
building_size                                                     36 m²   
carports                                                            NaN   
certificate                                  shm - sertifikat hak milik   
electricity                                                    2200 mah   
maid_bedrooms                                                       NaN   
maid_bathrooms                                                      NaN   
floors                                                              1.0   
building_age                                                        NaN   
property_condition                                                 baru   
building_orientation                                                NaN   
garages                                                             NaN   
furnishing                                               semi furnished   

                                                                   1391  
url                   https://www.rumah123.com/properti/bogor/hos109...  
price_in_rp                                                 470000000.0  
title                 Cluster Minimalis Langsung Huni Kpr Dp 10 Juta...  
address                                             Tajur Halang, Bogor  
district                                                   Tajur Halang  
city                                                              Bogor  
facilities                 Jalur Telepon,  AC, Taman,  Masjid, Keamanan  
property_type                                                     rumah  
ads_id                                                      hos10969299  
bedrooms                                                            2.0  
bathrooms                                                           1.0  
land_size                                                        147 m²  
building_size                                                     40 m²  
carports                                                            1.0  
certificate                                  shm - sertifikat hak milik  
electricity                                                    1300 mah  
maid_bedrooms                                                       NaN  
maid_bathrooms                                                      NaN  
floors                                                              1.0  
building_age                                                        NaN  
property_condition                                                 baru  
building_orientation                                                NaN  
garages                                                             1.0  
furnishing                                                  unfurnished

In notebook `1. Web Scraping`, we also scrap `estimated latitude and longitude` of each district, because the primary website doesn't provide any coordinate information.

We are going to join the `latitude and longitude` data using below codes. `Adress` column will be used as the `join key`.

In [19]:
lat_long_df = pd.read_csv('Scraped_Data/lat_long_complete.csv')
lat_long_df.head()

address                   lat_long  \
0         Bekasi, Bekasi   (-6.2849775, 106.970127)   
1           Setu, Bekasi   (-6.358777, 107.0348331)   
2  Harapan Indah, Bekasi  (-6.1817523, 106.9736839)   
3    Bekasi Kota, Bekasi   (-6.2845395, 106.973377)   
4       Cibitung, Bekasi   (-6.243801, 107.1036725)   

                                           gmaps_tag  
0                               Kota Bks, Jawa Barat  
1            Kec. Setu, Kabupaten Bekasi, Jawa Barat  
2  Harapan Indah, RT.005/RW.010, Medan Satria, Ke...  
3                       Bekasi, Kota Bks, Jawa Barat  
4        Kec. Cibitung, Kabupaten Bekasi, Jawa Barat

In [20]:
def split_lat_long(value):
    lat_long = ast.literal_eval(value)
    return lat_long

split_lat_long_vectd = vectorize(split_lat_long)
lat_long_df = lat_long_df.assign(
    lat=split_lat_long_vectd(lat_long_df.lat_long)[0],
    long=split_lat_long_vectd(lat_long_df.lat_long)[1],
)
lat_long_df.head()

address                   lat_long  \
0         Bekasi, Bekasi   (-6.2849775, 106.970127)   
1           Setu, Bekasi   (-6.358777, 107.0348331)   
2  Harapan Indah, Bekasi  (-6.1817523, 106.9736839)   
3    Bekasi Kota, Bekasi   (-6.2845395, 106.973377)   
4       Cibitung, Bekasi   (-6.243801, 107.1036725)   

                                           gmaps_tag       lat        long  
0                               Kota Bks, Jawa Barat -6.284978  106.970127  
1            Kec. Setu, Kabupaten Bekasi, Jawa Barat -6.358777  107.034833  
2  Harapan Indah, RT.005/RW.010, Medan Satria, Ke... -6.181752  106.973684  
3                       Bekasi, Kota Bks, Jawa Barat -6.284540  106.973377  
4        Kec. Cibitung, Kabupaten Bekasi, Jawa Barat -6.243801  107.103673

In [21]:
# merge dataframes
df = df.merge(
    right=lat_long_df.loc[:, ['address', 'lat', 'long']],
    on='address'
)
# re-arrange columns
cols = df.columns.to_list()
cols.insert(6, 'long')
cols.insert(6, 'lat')
cols_arranged = cols.copy()[:-2]
df = df[cols_arranged]

df.sample(2).T

1420  \
url                   https://www.rumah123.com/properti/bogor/hos113...   
price_in_rp                                                 300000000.0   
title                           Rumah Bagus Siap Huni Sudah di Renovasi   
address                                                  Jonggol, Bogor   
district                                                        Jonggol   
city                                                              Bogor   
lat                                                            -6.50635   
long                                                         107.055555   
facilities            Jalur Telepon,  Track Lari,  Lapangan Bulu Tan...   
property_type                                                     rumah   
ads_id                                                      hos11360366   
bedrooms                                                            2.0   
bathrooms                                                           1.0   
land_size                                                         72 m²   
building_size                                                     50 m²   
carports                                                            1.0   
certificate                                     hgb - hak guna bangunan   
electricity                                                    1300 mah   
maid_bedrooms                                                       NaN   
maid_bathrooms                                                      NaN   
floors                                                              1.0   
building_age                                                        NaN   
property_condition                                                bagus   
building_orientation                                              timur   
garages                                                             1.0   
furnishing                                                  unfurnished   

                                                                   2933  
url                   https://www.rumah123.com/properti/tangerang/ho...  
price_in_rp                                                1300000000.0  
title                 RUMAH MILLENIAL SIAP HUNI! LOKASI STRATEGIS SI...  
address                                             BSD City, Tangerang  
district                                                       BSD City  
city                                                          Tangerang  
lat                                                           -6.300733  
long                                                         106.586126  
facilities             Ac,  Keamanan, CCTV,  Jogging Track,  Taman, ...  
property_type                                                     rumah  
ads_id                                                      hos10046182  
bedrooms                                                            2.0  
bathrooms                                                           1.0  
land_size                                                         48 m²  
building_size                                                     45 m²  
carports                                                            1.0  
certificate                                  shm - sertifikat hak milik  
electricity                                                    2200 mah  
maid_bedrooms                                                       NaN  
maid_bathrooms                                                      NaN  
floors                                                              2.0  
building_age                                                     2022.0  
property_condition                                                bagus  
building_orientation                                            selatan  
garages                                                             1.0  
furnishing                                                    furnished

#### **Land Size, Building Size, Electricity**

Records of these columns is still in `string` format as (`value`, `unit`). We will extract only the number and rename the columns to inform the unit.

In [22]:
def get_value(value:str):
    if (type(value) == str):
        return float(value.strip().split(sep=' ')[0])
    else:
        return float(value)
    
get_value_vectd = vectorize(get_value)

In [23]:
df = df.assign(
    land_size=get_value_vectd(df.land_size),
    building_size=get_value_vectd(df.building_size),
    ).rename(
        columns={
            'land_size': 'land_size_m2',
            'building_size': 'building_size_m2'
        }
    )

df.sample(2).T

3422  \
url                   https://www.rumah123.com/properti/tangerang/ho...   
price_in_rp                                                2000000000.0   
title                 Rumah Baru Minimalis Siap Huni Strategis Di Nu...   
address                                         BSD Nusaloka, Tangerang   
district                                                   BSD Nusaloka   
city                                                          Tangerang   
lat                                                           -6.187515   
long                                                         106.518686   
facilities                      Taman, Masjid, Jogging Track,  Keamanan   
property_type                                                     rumah   
ads_id                                                      hos10939253   
bedrooms                                                            3.0   
bathrooms                                                           2.0   
land_size_m2                                                       98.0   
building_size_m2                                                  130.0   
carports                                                            NaN   
certificate                                  shm - sertifikat hak milik   
electricity                                                    2200 mah   
maid_bedrooms                                                       1.0   
maid_bathrooms                                                      1.0   
floors                                                              2.0   
building_age                                                     2022.0   
property_condition                                                 baru   
building_orientation                                         barat laut   
garages                                                             1.0   
furnishing                                               semi furnished   

                                                                   3353  
url                   https://www.rumah123.com/properti/tangerang/ho...  
price_in_rp                                                1600000000.0  
title                 Rumah Di Tanggerang Dekat Tol Karawaci 1 Idama...  
address                                       Tangerang Kota, Tangerang  
district                                                 Tangerang Kota  
city                                                          Tangerang  
lat                                                           -6.176687  
long                                                         106.650034  
facilities            Masjid,  Taman, Tempat Jemuran, Lapangan Bulu ...  
property_type                                                     rumah  
ads_id                                                      hos11112175  
bedrooms                                                            6.0  
bathrooms                                                           3.0  
land_size_m2                                                      140.0  
building_size_m2                                                  180.0  
carports                                                            1.0  
certificate                                  shm - sertifikat hak milik  
electricity                                                    2200 mah  
maid_bedrooms                                                       NaN  
maid_bathrooms                                                      NaN  
floors                                                              2.0  
building_age                                                     2020.0  
property_condition                                                  NaN  
building_orientation                                            selatan  
garages                                                             2.0  
furnishing                                               semi furnished

Let's inspect the `electricity`. The category of electricity power for residential in Indonesia should not varied vastly.

In [24]:
df.electricity.unique()

array(['4400 mah', '2200 mah', '3500 mah', '1300 mah', nan, '5500 mah',
       '6600 mah', '7700 mah', '3300 mah', '7600 mah', 'lainnya mah',
       '10600 mah', '900 mah', '47500 mah', '11000 mah', '8000 mah',
       '450 mah', '10000 mah', '53000 mah', '16500 mah', '13200 mah',
       '13900 mah', '17600 mah', '23000 mah', '41500 mah', '12700 mah',
       '13300 mah', '33000 mah', '24000 mah', '22000 mah', '9500 mah'],
      dtype=object)

Later we can replace the missing `nan` value with `lainnya mah`. And also, the electricity is naturally has an `ordinal` order, which must be considered in later analysis.

#### **Building Age**

Let's inspect the `Building Age` columns:

In [25]:
df.building_age.unique()

array([ 2017.,    nan,  2016.,  2013.,  2014.,  2015.,  2022.,  2020.,
        2010.,  2018.,  2011.,  2021.,  2006.,  2000.,  2023.,  2019.,
        2007.,  2009.,  2012.,  2004.,  1985.,  2008.,  2001.,  2005.,
        1994.,  2003.,  2052.,  2002.,  2024.,  1995.,  1870.,  1970.,
        2025.,  1986.,  1980.,  1996.,  1993., 20010.,  1990.,  1999.,
       20012.,  1988.,  1982.,  1998.,  1976.,  1977.,  1973.,  1901.,
        1992.])

Some concerns:

1. Based on its values, it is best to be explained as `year_built`. We will rename the columns.
2. Unfortunately we don't find the `date listed` information in the listing info since it is best to explain *what owner think their house priced in the year that the house is listed and also considering house age since first it been built*. But it is okay to assumme that at the time the listing is still advertised in the website then owner *did* consider the value adhere to current year valuation. So we can extract `building_age = year_built - 2022`.  
3. There are some values that ambiguous: `2052, 20010, 20012, 2025`. For values `2025`, it may be because house is available after future housing project will be completed at `2025` (but this justification is still not make sense for `2052`) 

In [26]:
df.rename(
    columns={'building_age': 'year_built'},
    inplace=True
)

In [27]:
years = [2052, 20010, 20012, 2025]
df[df.year_built.isin(years)].T

761   \
url                   https://www.rumah123.com/properti/bogor/hos111...   
price_in_rp                                                 570000000.0   
title                              rumah 1 Lanta murah angsuran 2jutaan   
address                                              Sentul City, Bogor   
district                                                    Sentul City   
city                                                              Bogor   
lat                                                            -6.51835   
long                                                         106.851279   
facilities             Jalur Telepon, Tempat Jemuran,  One Gate Syst...   
property_type                                                     rumah   
ads_id                                                      hos11148142   
bedrooms                                                            2.0   
bathrooms                                                           1.0   
land_size_m2                                                       72.0   
building_size_m2                                                   45.0   
carports                                                            1.0   
certificate                                  shm - sertifikat hak milik   
electricity                                                    1300 mah   
maid_bedrooms                                                       NaN   
maid_bathrooms                                                      NaN   
floors                                                              1.0   
year_built                                                       2052.0   
property_condition                                                 baru   
building_orientation                                              timur   
garages                                                             1.0   
furnishing                                                  unfurnished   

                                                                   1571  \
url                   https://www.rumah123.com/properti/depok/hos113...   
price_in_rp                                                 370000000.0   
title                  RUMAH MEWAH DENGAN DESAIN EROPA MURAH DI CITAYAM   
address                                                  Citayam, Depok   
district                                                        Citayam   
city                                                              Depok   
lat                                                           -6.444004   
long                                                         106.744265   
facilities            Tempat Jemuran,  Akses Parkir,  One Gate Syste...   
property_type                                                     rumah   
ads_id                                                      hos11336748   
bedrooms                                                            NaN   
bathrooms                                                           1.0   
land_size_m2                                                       65.0   
building_size_m2                                                   36.0   
carports                                                            1.0   
certificate                                  shm - sertifikat hak milik   
electricity                                                    1300 mah   
maid_bedrooms                                                       NaN   
maid_bathrooms                                                      NaN   
floors                                                              1.0   
year_built                                                       2025.0   
property_condition                                                 baru   
building_orientation                                            selatan   
garages                                                             1.0   
furnishing                                                  unfurnished   

               

After inspecting each of the records, it is safe to say that:

1. For `year_built > 2022`, let's just keep the value as it is, since it is better be explained as `building age = 0`.
2. For `year_built in [20010, 20012]`, based on `property_condition`, let's assume best case scenario to be `2010 and 2012`.

In [28]:
def building_age(year_built):
    if year_built <= 2022:
        return (2022 - year_built)
    elif year_built > 2022:
        return 0
    return year_built

building_age_vectd = vectorize(building_age)
df.loc[df.year_built == 20010, 'year_built'] = 2010
df.loc[df.year_built == 20012, 'year_built'] = 2012
df.insert(21, 'building_age', building_age_vectd(df.year_built))

df.building_age.unique()

d:\anaconda3\envs\general_ds\lib\site-packages\numpy\lib\function_base.py:2192: RuntimeWarning: invalid value encountered in ? (vectorized)
  outputs = ufunc(*inputs)


array([  5.,  nan,   6.,   9.,   8.,   7.,   0.,   2.,  12.,   4.,  11.,
         1.,  16.,  22.,   3.,  15.,  13.,  10.,  18.,  37.,  14.,  21.,
        17.,  28.,  19.,  20.,  27., 152.,  52.,  36.,  42.,  26.,  29.,
        32.,  23.,  34.,  40.,  24.,  46.,  45.,  49., 121.,  30.])

## 4. Considering the Missing Value

Missing values for column fields explained below can naturally be considired as `not provided` so can be replaced by `0` (`lainnya mah` for missing electricity type):

1. Maid Bedrooms
2. Maid Bathrooms
3. Carports
4. Garages
5. Electricity

In [29]:
fill_columns = ['maid_bedrooms', 'maid_bathrooms', 'carports', 'garages']

for column in fill_columns:
    df[column].fillna(0, inplace=True)

df['electricity'].fillna('lainnya mah', inplace=True)
df[
    df.maid_bedrooms.isna() | df.maid_bathrooms.isna() | df.carports.isna() | df.garages.isna() | df.electricity.isna()
    ]

Empty DataFrame
Columns: [url, price_in_rp, title, address, district, city, lat, long, facilities, property_type, ads_id, bedrooms, bathrooms, land_size_m2, building_size_m2, carports, certificate, electricity, maid_bedrooms, maid_bathrooms, floors, building_age, year_built, property_condition, building_orientation, garages, furnishing]
Index: []

[0 rows x 27 columns]

Other than aboves column fields, missing value is considered missing information (since it explains the essential characteristic of the house) and will be evaluated in later analysis.

## 4. Pre-Processed Data

Our preprocessed data looks like below sample. It is nice to change setting of number display format so that we can clearly identify the thousands separator.

In [33]:
pd.set_option('display.float_format', '{:,.2f}'.format)

df.sample(2).T

243   \
url                   https://www.rumah123.com/properti/bekasi/hos10...   
price_in_rp                                              500,000,000.00   
title                    Rumah Full Bata Merah Tidak Banjir di Jatiasih   
address                                               Jati Asih, Bekasi   
district                                                      Jati Asih   
city                                                             Bekasi   
lat                                                               -6.31   
long                                                             106.96   
facilities            Tempat Jemuran, Keamanan 24 jam,  CCTV, Taman,...   
property_type                                                     rumah   
ads_id                                                      hos10960046   
bedrooms                                                           2.00   
bathrooms                                                          1.00   
land_size_m2                                                      64.00   
building_size_m2                                                  47.00   
carports                                                           1.00   
certificate                                  shm - sertifikat hak milik   
electricity                                                    2200 mah   
maid_bedrooms                                                      0.00   
maid_bathrooms                                                     0.00   
floors                                                             1.00   
building_age                                                       0.00   
year_built                                                     2,022.00   
property_condition                                                 baru   
building_orientation                                                NaN   
garages                                                            0.00   
furnishing                                                  unfurnished   

                                                                   2523  
url                   https://www.rumah123.com/properti/jakarta-timu...  
price_in_rp                                              389,000,000.00  
title                 Rumah Murah 2 Lantai Dekat Pasar Pramuka Jakar...  
address                                         Matraman, Jakarta Timur  
district                                                       Matraman  
city                                                      Jakarta Timur  
lat                                                               -6.20  
long                                                             106.86  
facilities                   Keamanan 24 jam, One Gate System, Keamanan  
property_type                                                     rumah  
ads_id                                                      hos11324434  
bedrooms                                                           2.00  
bathrooms                                                          1.00  
land_size_m2                                                      16.00  
building_size_m2                                                  38.00  
carports                                                           0.00  
certificate                                  shm - sertifikat hak milik  
electricity                                                    2200 mah  
maid_bedrooms                                                      0.00  
maid_bathrooms                                                     0.00  
floors                                                             2.00  
building_age                                                       0.00  
year_built                                                     2,022.00  
property_condition                                                 baru  
building_orientation                                                NaN  
garages                                   

In [35]:
df.to_csv('Scraped_Data/jabodetabek_house_price.csv', index=False)